server {
    listen 80;
    server_name pixelforge-grupoN.lab.umng.edu.co;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name pixelforge-grupoN.lab.umng.edu.co;
    ssl_certificate     /etc/letsencrypt/live/pixelforge-grupoN.lab.umng.edu.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pixelforge-grupoN.lab.umng.edu.co/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    # TODO Parcial 3.1: agregar headers de seguridad

    # Juego Phaser
    location / {
        root /var/www/pixelforge/game;
        try_files $uri $uri/ /index.html;
    }
    # Portal Angular
    location /portal/ {
        alias /var/www/pixelforge/dist/pixelforge-portal/;
        try_files $uri $uri/ /portal/index.html;
    }
    location /api/ {
        proxy_pass http://10.0.0.11:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
